"""add foreign key to Review

Revision ID: 872050a9e8a7
Revises: 676a4773b85b
Create Date: 2024-07-07 23:51:27.991406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872050a9e8a7'
down_revision = '676a4773b85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_employees_employee_id_employees'), 'employees', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employees_employee_id_employees'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'employee_id')
    # ### end Alembic commands ###
